---
- name: Change user password on ESXI hosts
  hosts: "{{ match_host }}"
  become: false
  gather_facts: false
  #pre_tasks:
  #  - include_vars: vars.yml
  tasks:
    - name: Change user password
      vmware_local_user_manager:
        hostname: '{{ inventory_hostname }}'
        #username: '{{ vcenter_username }}'
        #password: '{{ vcenter_password }}'
        local_user_name: "{{ username }}"
        local_user_password: "{{ password }}"
        state: present
        validate_certs: no
      delegate_to: localhost